/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link ReferrerTokenState}
 * @category Accounts
 * @category generated
 */
export type ReferrerTokenStateArgs = {
  referrer: web3.PublicKey
  mint: web3.PublicKey
  amountUnclaimedSf: beet.bignum
  amountCumulativeSf: beet.bignum
  bump: beet.bignum
  padding: beet.bignum[] /* size: 31 */
}

export const referrerTokenStateDiscriminator = [
  39, 15, 208, 77, 32, 195, 105, 56,
]
/**
 * Holds the data for the {@link ReferrerTokenState} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class ReferrerTokenState implements ReferrerTokenStateArgs {
  private constructor(
    readonly referrer: web3.PublicKey,
    readonly mint: web3.PublicKey,
    readonly amountUnclaimedSf: beet.bignum,
    readonly amountCumulativeSf: beet.bignum,
    readonly bump: beet.bignum,
    readonly padding: beet.bignum[] /* size: 31 */
  ) {}

  /**
   * Creates a {@link ReferrerTokenState} instance from the provided args.
   */
  static fromArgs(args: ReferrerTokenStateArgs) {
    return new ReferrerTokenState(
      args.referrer,
      args.mint,
      args.amountUnclaimedSf,
      args.amountCumulativeSf,
      args.bump,
      args.padding
    )
  }

  /**
   * Deserializes the {@link ReferrerTokenState} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [ReferrerTokenState, number] {
    return ReferrerTokenState.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link ReferrerTokenState} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<ReferrerTokenState> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find ReferrerTokenState account at ${address}`)
    }
    return ReferrerTokenState.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'HUHJsverovPJN3sVtv8J8D48fKzeajRtz3Ga4Zmh4RLA'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, referrerTokenStateBeet)
  }

  /**
   * Deserializes the {@link ReferrerTokenState} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [ReferrerTokenState, number] {
    return referrerTokenStateBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link ReferrerTokenState} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return referrerTokenStateBeet.serialize({
      accountDiscriminator: referrerTokenStateDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link ReferrerTokenState}
   */
  static get byteSize() {
    return referrerTokenStateBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link ReferrerTokenState} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      ReferrerTokenState.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link ReferrerTokenState} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === ReferrerTokenState.byteSize
  }

  /**
   * Returns a readable version of {@link ReferrerTokenState} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      referrer: this.referrer.toBase58(),
      mint: this.mint.toBase58(),
      amountUnclaimedSf: (() => {
        const x = <{ toNumber: () => number }>this.amountUnclaimedSf
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      amountCumulativeSf: (() => {
        const x = <{ toNumber: () => number }>this.amountCumulativeSf
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      bump: (() => {
        const x = <{ toNumber: () => number }>this.bump
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      padding: this.padding,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const referrerTokenStateBeet = new beet.BeetStruct<
  ReferrerTokenState,
  ReferrerTokenStateArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['referrer', beetSolana.publicKey],
    ['mint', beetSolana.publicKey],
    ['amountUnclaimedSf', beet.u128],
    ['amountCumulativeSf', beet.u128],
    ['bump', beet.u64],
    ['padding', beet.uniformFixedSizeArray(beet.u64, 31)],
  ],
  ReferrerTokenState.fromArgs,
  'ReferrerTokenState'
)
