/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category WritePythPrice
 * @category generated
 */
export type WritePythPriceInstructionArgs = {
  price: beet.bignum
  expo: number
  slot: beet.bignum
  timestampSec: beet.bignum
}
/**
 * @category Instructions
 * @category WritePythPrice
 * @category generated
 */
export const writePythPriceStruct = new beet.BeetArgsStruct<
  WritePythPriceInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['price', beet.i64],
    ['expo', beet.i32],
    ['slot', beet.i64],
    ['timestampSec', beet.i64],
  ],
  'WritePythPriceInstructionArgs'
)
/**
 * Accounts required by the _writePythPrice_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_, **signer**] target
 * @category Instructions
 * @category WritePythPrice
 * @category generated
 */
export type WritePythPriceInstructionAccounts = {
  signer: web3.PublicKey
  target: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const writePythPriceInstructionDiscriminator = [
  89, 56, 62, 212, 86, 217, 235, 132,
]

/**
 * Creates a _WritePythPrice_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category WritePythPrice
 * @category generated
 */
export function createWritePythPriceInstruction(
  accounts: WritePythPriceInstructionAccounts,
  args: WritePythPriceInstructionArgs,
  programId = new web3.PublicKey('6Lh68KvhjwFGUENYh97S5BdLubB91bEcgKc2BuU2M13q')
) {
  const [data] = writePythPriceStruct.serialize({
    instructionDiscriminator: writePythPriceInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.target,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
