/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category KlendDeposit
 * @category generated
 */
export type KlendDepositInstructionArgs = {
  amount: beet.bignum
}
/**
 * @category Instructions
 * @category KlendDeposit
 * @category generated
 */
export const klendDepositStruct = new beet.BeetArgsStruct<
  KlendDepositInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['amount', beet.u64],
  ],
  'KlendDepositInstructionArgs'
)
/**
 * Accounts required by the _klendDeposit_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_] bestlendUserAccount
 * @property [_writable_] userSourceLiquidity
 * @property [_writable_] bestlendUserSourceLiquidity
 * @property [] klendProgram
 * @property [_writable_] obligation
 * @property [] lendingMarket
 * @property [_writable_] reserve
 * @property [_writable_] reserveLiquiditySupply
 * @property [_writable_] reserveCollateralMint
 * @property [_writable_] reserveDestinationDepositCollateral
 * @property [] lendingMarketAuthority
 * @property [_writable_] userDestinationCollateral
 * @property [] instructionSysvarAccount
 * @category Instructions
 * @category KlendDeposit
 * @category generated
 */
export type KlendDepositInstructionAccounts = {
  signer: web3.PublicKey
  bestlendUserAccount: web3.PublicKey
  userSourceLiquidity: web3.PublicKey
  bestlendUserSourceLiquidity: web3.PublicKey
  tokenProgram?: web3.PublicKey
  klendProgram: web3.PublicKey
  obligation: web3.PublicKey
  lendingMarket: web3.PublicKey
  reserve: web3.PublicKey
  reserveLiquiditySupply: web3.PublicKey
  reserveCollateralMint: web3.PublicKey
  reserveDestinationDepositCollateral: web3.PublicKey
  lendingMarketAuthority: web3.PublicKey
  userDestinationCollateral: web3.PublicKey
  instructionSysvarAccount: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const klendDepositInstructionDiscriminator = [
  191, 11, 149, 169, 30, 229, 88, 244,
]

/**
 * Creates a _KlendDeposit_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category KlendDeposit
 * @category generated
 */
export function createKlendDepositInstruction(
  accounts: KlendDepositInstructionAccounts,
  args: KlendDepositInstructionArgs,
  programId = new web3.PublicKey('hackF7pNZ7dGZCGXaiPNnzxkSoyrBkyEyDTpywK9KJs')
) {
  const [data] = klendDepositStruct.serialize({
    instructionDiscriminator: klendDepositInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.bestlendUserAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userSourceLiquidity,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.bestlendUserSourceLiquidity,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.klendProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.obligation,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarket,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.reserve,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveLiquiditySupply,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveCollateralMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveDestinationDepositCollateral,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarketAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.userDestinationCollateral,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.instructionSysvarAccount,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
