/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category KlendRepay
 * @category generated
 */
export type KlendRepayInstructionArgs = {
  amount: beet.bignum
}
/**
 * @category Instructions
 * @category KlendRepay
 * @category generated
 */
export const klendRepayStruct = new beet.BeetArgsStruct<
  KlendRepayInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['amount', beet.u64],
  ],
  'KlendRepayInstructionArgs'
)
/**
 * Accounts required by the _klendRepay_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_] bestlendUserAccount
 * @property [_writable_] userSourceLiquidity
 * @property [_writable_] bestlendUserSourceLiquidity
 * @property [] klendProgram
 * @property [_writable_] obligation
 * @property [] lendingMarket
 * @property [_writable_] reserve
 * @property [_writable_] reserveDestinationLiquidity
 * @property [] instructionSysvarAccount
 * @category Instructions
 * @category KlendRepay
 * @category generated
 */
export type KlendRepayInstructionAccounts = {
  signer: web3.PublicKey
  bestlendUserAccount: web3.PublicKey
  userSourceLiquidity: web3.PublicKey
  bestlendUserSourceLiquidity: web3.PublicKey
  klendProgram: web3.PublicKey
  obligation: web3.PublicKey
  lendingMarket: web3.PublicKey
  reserve: web3.PublicKey
  reserveDestinationLiquidity: web3.PublicKey
  instructionSysvarAccount: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const klendRepayInstructionDiscriminator = [
  197, 65, 20, 75, 199, 196, 184, 231,
]

/**
 * Creates a _KlendRepay_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category KlendRepay
 * @category generated
 */
export function createKlendRepayInstruction(
  accounts: KlendRepayInstructionAccounts,
  args: KlendRepayInstructionArgs,
  programId = new web3.PublicKey('hackF7pNZ7dGZCGXaiPNnzxkSoyrBkyEyDTpywK9KJs')
) {
  const [data] = klendRepayStruct.serialize({
    instructionDiscriminator: klendRepayInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.bestlendUserAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userSourceLiquidity,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.bestlendUserSourceLiquidity,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.klendProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.obligation,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarket,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.reserve,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveDestinationLiquidity,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.instructionSysvarAccount,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
