/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category KlendWithdraw
 * @category generated
 */
export type KlendWithdrawInstructionArgs = {
  amount: beet.bignum
}
/**
 * @category Instructions
 * @category KlendWithdraw
 * @category generated
 */
export const klendWithdrawStruct = new beet.BeetArgsStruct<
  KlendWithdrawInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['amount', beet.u64],
  ],
  'KlendWithdrawInstructionArgs'
)
/**
 * Accounts required by the _klendWithdraw_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_] bestlendUserAccount
 * @property [_writable_] userDestinationLiquidity
 * @property [] instructions
 * @property [] klendProgram
 * @property [_writable_] obligation
 * @property [] lendingMarket
 * @property [_writable_] reserve
 * @property [_writable_] reserveLiquiditySupply
 * @property [_writable_] reserveCollateralMint
 * @property [_writable_] reserveSourceDepositCollateral
 * @property [] lendingMarketAuthority
 * @property [_writable_] userDestinationCollateral
 * @category Instructions
 * @category KlendWithdraw
 * @category generated
 */
export type KlendWithdrawInstructionAccounts = {
  signer: web3.PublicKey
  bestlendUserAccount: web3.PublicKey
  userDestinationLiquidity: web3.PublicKey
  tokenProgram?: web3.PublicKey
  instructions: web3.PublicKey
  klendProgram: web3.PublicKey
  obligation: web3.PublicKey
  lendingMarket: web3.PublicKey
  reserve: web3.PublicKey
  reserveLiquiditySupply: web3.PublicKey
  reserveCollateralMint: web3.PublicKey
  reserveSourceDepositCollateral: web3.PublicKey
  lendingMarketAuthority: web3.PublicKey
  userDestinationCollateral: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const klendWithdrawInstructionDiscriminator = [
  105, 129, 246, 107, 135, 230, 195, 12,
]

/**
 * Creates a _KlendWithdraw_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category KlendWithdraw
 * @category generated
 */
export function createKlendWithdrawInstruction(
  accounts: KlendWithdrawInstructionAccounts,
  args: KlendWithdrawInstructionArgs,
  programId = new web3.PublicKey('hackF7pNZ7dGZCGXaiPNnzxkSoyrBkyEyDTpywK9KJs')
) {
  const [data] = klendWithdrawStruct.serialize({
    instructionDiscriminator: klendWithdrawInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.bestlendUserAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userDestinationLiquidity,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.instructions,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.klendProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.obligation,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarket,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.reserve,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveLiquiditySupply,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveCollateralMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveSourceDepositCollateral,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarketAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.userDestinationCollateral,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
