/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category KlendBorrow
 * @category generated
 */
export type KlendBorrowInstructionArgs = {
  amount: beet.bignum
}
/**
 * @category Instructions
 * @category KlendBorrow
 * @category generated
 */
export const klendBorrowStruct = new beet.BeetArgsStruct<
  KlendBorrowInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['amount', beet.u64],
  ],
  'KlendBorrowInstructionArgs'
)
/**
 * Accounts required by the _klendBorrow_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_] bestlendUserAccount
 * @property [_writable_] userDestinationLiquidity
 * @property [] instructions
 * @property [] klendProgram
 * @property [_writable_] obligation
 * @property [] lendingMarket
 * @property [_writable_] reserve
 * @property [] lendingMarketAuthority
 * @property [_writable_] reserveSourceLiquidity
 * @property [_writable_] borrowReserveLiquidityFeeReceiver
 * @category Instructions
 * @category KlendBorrow
 * @category generated
 */
export type KlendBorrowInstructionAccounts = {
  signer: web3.PublicKey
  bestlendUserAccount: web3.PublicKey
  userDestinationLiquidity: web3.PublicKey
  instructions: web3.PublicKey
  klendProgram: web3.PublicKey
  obligation: web3.PublicKey
  lendingMarket: web3.PublicKey
  reserve: web3.PublicKey
  lendingMarketAuthority: web3.PublicKey
  reserveSourceLiquidity: web3.PublicKey
  borrowReserveLiquidityFeeReceiver: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const klendBorrowInstructionDiscriminator = [
  32, 43, 209, 210, 214, 46, 120, 139,
]

/**
 * Creates a _KlendBorrow_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category KlendBorrow
 * @category generated
 */
export function createKlendBorrowInstruction(
  accounts: KlendBorrowInstructionAccounts,
  args: KlendBorrowInstructionArgs,
  programId = new web3.PublicKey('hackF7pNZ7dGZCGXaiPNnzxkSoyrBkyEyDTpywK9KJs')
) {
  const [data] = klendBorrowStruct.serialize({
    instructionDiscriminator: klendBorrowInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.bestlendUserAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userDestinationLiquidity,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.instructions,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.klendProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.obligation,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarket,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.reserve,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarketAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveSourceLiquidity,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.borrowReserveLiquidityFeeReceiver,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
