/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category DepositReserveLiquidity
 * @category generated
 */
export type DepositReserveLiquidityInstructionArgs = {
  liquidityAmount: beet.bignum
}
/**
 * @category Instructions
 * @category DepositReserveLiquidity
 * @category generated
 */
export const depositReserveLiquidityStruct = new beet.BeetArgsStruct<
  DepositReserveLiquidityInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['liquidityAmount', beet.u64],
  ],
  'DepositReserveLiquidityInstructionArgs'
)
/**
 * Accounts required by the _depositReserveLiquidity_ instruction
 *
 * @property [**signer**] owner
 * @property [_writable_] reserve
 * @property [] lendingMarket
 * @property [] lendingMarketAuthority
 * @property [_writable_] reserveLiquiditySupply
 * @property [_writable_] reserveCollateralMint
 * @property [_writable_] userSourceLiquidity
 * @property [_writable_] userDestinationCollateral
 * @category Instructions
 * @category DepositReserveLiquidity
 * @category generated
 */
export type DepositReserveLiquidityInstructionAccounts = {
  owner: web3.PublicKey
  reserve: web3.PublicKey
  lendingMarket: web3.PublicKey
  lendingMarketAuthority: web3.PublicKey
  reserveLiquiditySupply: web3.PublicKey
  reserveCollateralMint: web3.PublicKey
  userSourceLiquidity: web3.PublicKey
  userDestinationCollateral: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const depositReserveLiquidityInstructionDiscriminator = [
  169, 201, 30, 126, 6, 205, 102, 68,
]

/**
 * Creates a _DepositReserveLiquidity_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category DepositReserveLiquidity
 * @category generated
 */
export function createDepositReserveLiquidityInstruction(
  accounts: DepositReserveLiquidityInstructionAccounts,
  args: DepositReserveLiquidityInstructionArgs,
  programId = new web3.PublicKey('HUHJsverovPJN3sVtv8J8D48fKzeajRtz3Ga4Zmh4RLA')
) {
  const [data] = depositReserveLiquidityStruct.serialize({
    instructionDiscriminator: depositReserveLiquidityInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.owner,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.reserve,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarket,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarketAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveLiquiditySupply,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveCollateralMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userSourceLiquidity,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userDestinationCollateral,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
