/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category FlashBorrowReserveLiquidity
 * @category generated
 */
export type FlashBorrowReserveLiquidityInstructionArgs = {
  liquidityAmount: beet.bignum
}
/**
 * @category Instructions
 * @category FlashBorrowReserveLiquidity
 * @category generated
 */
export const flashBorrowReserveLiquidityStruct = new beet.BeetArgsStruct<
  FlashBorrowReserveLiquidityInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['liquidityAmount', beet.u64],
  ],
  'FlashBorrowReserveLiquidityInstructionArgs'
)
/**
 * Accounts required by the _flashBorrowReserveLiquidity_ instruction
 *
 * @property [**signer**] userTransferAuthority
 * @property [] lendingMarketAuthority
 * @property [] lendingMarket
 * @property [_writable_] reserve
 * @property [_writable_] reserveSourceLiquidity
 * @property [_writable_] userDestinationLiquidity
 * @property [_writable_] reserveLiquidityFeeReceiver
 * @property [_writable_] referrerTokenState (optional)
 * @property [_writable_] referrerAccount (optional)
 * @property [] sysvarInfo
 * @category Instructions
 * @category FlashBorrowReserveLiquidity
 * @category generated
 */
export type FlashBorrowReserveLiquidityInstructionAccounts = {
  userTransferAuthority: web3.PublicKey
  lendingMarketAuthority: web3.PublicKey
  lendingMarket: web3.PublicKey
  reserve: web3.PublicKey
  reserveSourceLiquidity: web3.PublicKey
  userDestinationLiquidity: web3.PublicKey
  reserveLiquidityFeeReceiver: web3.PublicKey
  referrerTokenState?: web3.PublicKey
  referrerAccount?: web3.PublicKey
  sysvarInfo: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const flashBorrowReserveLiquidityInstructionDiscriminator = [
  135, 231, 52, 167, 7, 52, 212, 193,
]

/**
 * Creates a _FlashBorrowReserveLiquidity_ instruction.
 *
 * Optional accounts that are not provided default to the program ID since
 * this was indicated in the IDL from which this instruction was generated.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category FlashBorrowReserveLiquidity
 * @category generated
 */
export function createFlashBorrowReserveLiquidityInstruction(
  accounts: FlashBorrowReserveLiquidityInstructionAccounts,
  args: FlashBorrowReserveLiquidityInstructionArgs,
  programId = new web3.PublicKey('HUHJsverovPJN3sVtv8J8D48fKzeajRtz3Ga4Zmh4RLA')
) {
  const [data] = flashBorrowReserveLiquidityStruct.serialize({
    instructionDiscriminator:
      flashBorrowReserveLiquidityInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.userTransferAuthority,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.lendingMarketAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarket,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.reserve,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveSourceLiquidity,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userDestinationLiquidity,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveLiquidityFeeReceiver,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.referrerTokenState ?? programId,
      isWritable: accounts.referrerTokenState != null,
      isSigner: false,
    },
    {
      pubkey: accounts.referrerAccount ?? programId,
      isWritable: accounts.referrerAccount != null,
      isSigner: false,
    },
    {
      pubkey: accounts.sysvarInfo,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
