/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category FlashRepayReserveLiquidity
 * @category generated
 */
export type FlashRepayReserveLiquidityInstructionArgs = {
  liquidityAmount: beet.bignum
  borrowInstructionIndex: number
}
/**
 * @category Instructions
 * @category FlashRepayReserveLiquidity
 * @category generated
 */
export const flashRepayReserveLiquidityStruct = new beet.BeetArgsStruct<
  FlashRepayReserveLiquidityInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['liquidityAmount', beet.u64],
    ['borrowInstructionIndex', beet.u8],
  ],
  'FlashRepayReserveLiquidityInstructionArgs'
)
/**
 * Accounts required by the _flashRepayReserveLiquidity_ instruction
 *
 * @property [**signer**] userTransferAuthority
 * @property [] lendingMarketAuthority
 * @property [] lendingMarket
 * @property [_writable_] reserve
 * @property [_writable_] reserveDestinationLiquidity
 * @property [_writable_] userSourceLiquidity
 * @property [_writable_] reserveLiquidityFeeReceiver
 * @property [_writable_] referrerTokenState (optional)
 * @property [_writable_] referrerAccount (optional)
 * @property [] sysvarInfo
 * @category Instructions
 * @category FlashRepayReserveLiquidity
 * @category generated
 */
export type FlashRepayReserveLiquidityInstructionAccounts = {
  userTransferAuthority: web3.PublicKey
  lendingMarketAuthority: web3.PublicKey
  lendingMarket: web3.PublicKey
  reserve: web3.PublicKey
  reserveDestinationLiquidity: web3.PublicKey
  userSourceLiquidity: web3.PublicKey
  reserveLiquidityFeeReceiver: web3.PublicKey
  referrerTokenState?: web3.PublicKey
  referrerAccount?: web3.PublicKey
  sysvarInfo: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const flashRepayReserveLiquidityInstructionDiscriminator = [
  185, 117, 0, 203, 96, 245, 180, 186,
]

/**
 * Creates a _FlashRepayReserveLiquidity_ instruction.
 *
 * Optional accounts that are not provided default to the program ID since
 * this was indicated in the IDL from which this instruction was generated.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category FlashRepayReserveLiquidity
 * @category generated
 */
export function createFlashRepayReserveLiquidityInstruction(
  accounts: FlashRepayReserveLiquidityInstructionAccounts,
  args: FlashRepayReserveLiquidityInstructionArgs,
  programId = new web3.PublicKey('HUHJsverovPJN3sVtv8J8D48fKzeajRtz3Ga4Zmh4RLA')
) {
  const [data] = flashRepayReserveLiquidityStruct.serialize({
    instructionDiscriminator:
      flashRepayReserveLiquidityInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.userTransferAuthority,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.lendingMarketAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarket,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.reserve,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveDestinationLiquidity,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userSourceLiquidity,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveLiquidityFeeReceiver,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.referrerTokenState ?? programId,
      isWritable: accounts.referrerTokenState != null,
      isSigner: false,
    },
    {
      pubkey: accounts.referrerAccount ?? programId,
      isWritable: accounts.referrerAccount != null,
      isSigner: false,
    },
    {
      pubkey: accounts.sysvarInfo,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
