/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * @category Instructions
 * @category InitUserMetadata
 * @category generated
 */
export type InitUserMetadataInstructionArgs = {
  userLookupTable: web3.PublicKey
}
/**
 * @category Instructions
 * @category InitUserMetadata
 * @category generated
 */
export const initUserMetadataStruct = new beet.BeetArgsStruct<
  InitUserMetadataInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['userLookupTable', beetSolana.publicKey],
  ],
  'InitUserMetadataInstructionArgs'
)
/**
 * Accounts required by the _initUserMetadata_ instruction
 *
 * @property [**signer**] owner
 * @property [_writable_, **signer**] feePayer
 * @property [_writable_] userMetadata
 * @property [] referrerUserMetadata (optional)
 * @category Instructions
 * @category InitUserMetadata
 * @category generated
 */
export type InitUserMetadataInstructionAccounts = {
  owner: web3.PublicKey
  feePayer: web3.PublicKey
  userMetadata: web3.PublicKey
  referrerUserMetadata?: web3.PublicKey
  rent?: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const initUserMetadataInstructionDiscriminator = [
  117, 169, 176, 69, 197, 23, 15, 162,
]

/**
 * Creates a _InitUserMetadata_ instruction.
 *
 * Optional accounts that are not provided default to the program ID since
 * this was indicated in the IDL from which this instruction was generated.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category InitUserMetadata
 * @category generated
 */
export function createInitUserMetadataInstruction(
  accounts: InitUserMetadataInstructionAccounts,
  args: InitUserMetadataInstructionArgs,
  programId = new web3.PublicKey('HUHJsverovPJN3sVtv8J8D48fKzeajRtz3Ga4Zmh4RLA')
) {
  const [data] = initUserMetadataStruct.serialize({
    instructionDiscriminator: initUserMetadataInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.owner,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.feePayer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.userMetadata,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.referrerUserMetadata ?? programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
