/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category RedeemReserveCollateral
 * @category generated
 */
export type RedeemReserveCollateralInstructionArgs = {
  collateralAmount: beet.bignum
}
/**
 * @category Instructions
 * @category RedeemReserveCollateral
 * @category generated
 */
export const redeemReserveCollateralStruct = new beet.BeetArgsStruct<
  RedeemReserveCollateralInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['collateralAmount', beet.u64],
  ],
  'RedeemReserveCollateralInstructionArgs'
)
/**
 * Accounts required by the _redeemReserveCollateral_ instruction
 *
 * @property [**signer**] owner
 * @property [] lendingMarket
 * @property [_writable_] reserve
 * @property [] lendingMarketAuthority
 * @property [_writable_] reserveCollateralMint
 * @property [_writable_] reserveLiquiditySupply
 * @property [_writable_] userSourceCollateral
 * @property [_writable_] userDestinationLiquidity
 * @category Instructions
 * @category RedeemReserveCollateral
 * @category generated
 */
export type RedeemReserveCollateralInstructionAccounts = {
  owner: web3.PublicKey
  lendingMarket: web3.PublicKey
  reserve: web3.PublicKey
  lendingMarketAuthority: web3.PublicKey
  reserveCollateralMint: web3.PublicKey
  reserveLiquiditySupply: web3.PublicKey
  userSourceCollateral: web3.PublicKey
  userDestinationLiquidity: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const redeemReserveCollateralInstructionDiscriminator = [
  234, 117, 181, 125, 185, 142, 220, 29,
]

/**
 * Creates a _RedeemReserveCollateral_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category RedeemReserveCollateral
 * @category generated
 */
export function createRedeemReserveCollateralInstruction(
  accounts: RedeemReserveCollateralInstructionAccounts,
  args: RedeemReserveCollateralInstructionArgs,
  programId = new web3.PublicKey('HUHJsverovPJN3sVtv8J8D48fKzeajRtz3Ga4Zmh4RLA')
) {
  const [data] = redeemReserveCollateralStruct.serialize({
    instructionDiscriminator: redeemReserveCollateralInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.owner,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.lendingMarket,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.reserve,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarketAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveCollateralMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveLiquiditySupply,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userSourceCollateral,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userDestinationLiquidity,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
