/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category RefreshObligation
 * @category generated
 */
export const refreshObligationStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'RefreshObligationInstructionArgs'
)
/**
 * Accounts required by the _refreshObligation_ instruction
 *
 * @property [] lendingMarket
 * @property [_writable_] obligation
 * @category Instructions
 * @category RefreshObligation
 * @category generated
 */
export type RefreshObligationInstructionAccounts = {
  lendingMarket: web3.PublicKey
  obligation: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const refreshObligationInstructionDiscriminator = [
  33, 132, 147, 228, 151, 192, 72, 89,
]

/**
 * Creates a _RefreshObligation_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category RefreshObligation
 * @category generated
 */
export function createRefreshObligationInstruction(
  accounts: RefreshObligationInstructionAccounts,
  programId = new web3.PublicKey('HUHJsverovPJN3sVtv8J8D48fKzeajRtz3Ga4Zmh4RLA')
) {
  const [data] = refreshObligationStruct.serialize({
    instructionDiscriminator: refreshObligationInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.lendingMarket,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.obligation,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
