/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category RefreshReserve
 * @category generated
 */
export const refreshReserveStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'RefreshReserveInstructionArgs'
)
/**
 * Accounts required by the _refreshReserve_ instruction
 *
 * @property [_writable_] reserve
 * @property [] lendingMarket
 * @property [] pythOracle (optional)
 * @property [] switchboardPriceOracle (optional)
 * @property [] switchboardTwapOracle (optional)
 * @property [] scopePrices (optional)
 * @category Instructions
 * @category RefreshReserve
 * @category generated
 */
export type RefreshReserveInstructionAccounts = {
  reserve: web3.PublicKey
  lendingMarket: web3.PublicKey
  pythOracle?: web3.PublicKey
  switchboardPriceOracle?: web3.PublicKey
  switchboardTwapOracle?: web3.PublicKey
  scopePrices?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const refreshReserveInstructionDiscriminator = [
  2, 218, 138, 235, 79, 201, 25, 102,
]

/**
 * Creates a _RefreshReserve_ instruction.
 *
 * Optional accounts that are not provided default to the program ID since
 * this was indicated in the IDL from which this instruction was generated.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category RefreshReserve
 * @category generated
 */
export function createRefreshReserveInstruction(
  accounts: RefreshReserveInstructionAccounts,
  programId = new web3.PublicKey('HUHJsverovPJN3sVtv8J8D48fKzeajRtz3Ga4Zmh4RLA')
) {
  const [data] = refreshReserveStruct.serialize({
    instructionDiscriminator: refreshReserveInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.reserve,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarket,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.pythOracle ?? programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.switchboardPriceOracle ?? programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.switchboardTwapOracle ?? programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.scopePrices ?? programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
