/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category RepayObligationLiquidity
 * @category generated
 */
export type RepayObligationLiquidityInstructionArgs = {
  liquidityAmount: beet.bignum
}
/**
 * @category Instructions
 * @category RepayObligationLiquidity
 * @category generated
 */
export const repayObligationLiquidityStruct = new beet.BeetArgsStruct<
  RepayObligationLiquidityInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['liquidityAmount', beet.u64],
  ],
  'RepayObligationLiquidityInstructionArgs'
)
/**
 * Accounts required by the _repayObligationLiquidity_ instruction
 *
 * @property [**signer**] owner
 * @property [_writable_] obligation
 * @property [] lendingMarket
 * @property [_writable_] repayReserve
 * @property [_writable_] reserveDestinationLiquidity
 * @property [_writable_] userSourceLiquidity
 * @property [] instructionSysvarAccount
 * @category Instructions
 * @category RepayObligationLiquidity
 * @category generated
 */
export type RepayObligationLiquidityInstructionAccounts = {
  owner: web3.PublicKey
  obligation: web3.PublicKey
  lendingMarket: web3.PublicKey
  repayReserve: web3.PublicKey
  reserveDestinationLiquidity: web3.PublicKey
  userSourceLiquidity: web3.PublicKey
  tokenProgram?: web3.PublicKey
  instructionSysvarAccount: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const repayObligationLiquidityInstructionDiscriminator = [
  145, 178, 13, 225, 76, 240, 147, 72,
]

/**
 * Creates a _RepayObligationLiquidity_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category RepayObligationLiquidity
 * @category generated
 */
export function createRepayObligationLiquidityInstruction(
  accounts: RepayObligationLiquidityInstructionAccounts,
  args: RepayObligationLiquidityInstructionArgs,
  programId = new web3.PublicKey('HUHJsverovPJN3sVtv8J8D48fKzeajRtz3Ga4Zmh4RLA')
) {
  const [data] = repayObligationLiquidityStruct.serialize({
    instructionDiscriminator: repayObligationLiquidityInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.owner,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.obligation,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarket,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.repayReserve,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveDestinationLiquidity,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userSourceLiquidity,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.instructionSysvarAccount,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
