/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category UpdateSingleReserveConfig
 * @category generated
 */
export type UpdateSingleReserveConfigInstructionArgs = {
  mode: beet.bignum
  value: number[] /* size: 32 */
}
/**
 * @category Instructions
 * @category UpdateSingleReserveConfig
 * @category generated
 */
export const updateSingleReserveConfigStruct = new beet.BeetArgsStruct<
  UpdateSingleReserveConfigInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['mode', beet.u64],
    ['value', beet.uniformFixedSizeArray(beet.u8, 32)],
  ],
  'UpdateSingleReserveConfigInstructionArgs'
)
/**
 * Accounts required by the _updateSingleReserveConfig_ instruction
 *
 * @property [**signer**] lendingMarketOwner
 * @property [] lendingMarket
 * @property [_writable_] reserve
 * @category Instructions
 * @category UpdateSingleReserveConfig
 * @category generated
 */
export type UpdateSingleReserveConfigInstructionAccounts = {
  lendingMarketOwner: web3.PublicKey
  lendingMarket: web3.PublicKey
  reserve: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const updateSingleReserveConfigInstructionDiscriminator = [
  248, 195, 192, 90, 204, 42, 162, 233,
]

/**
 * Creates a _UpdateSingleReserveConfig_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category UpdateSingleReserveConfig
 * @category generated
 */
export function createUpdateSingleReserveConfigInstruction(
  accounts: UpdateSingleReserveConfigInstructionAccounts,
  args: UpdateSingleReserveConfigInstructionArgs,
  programId = new web3.PublicKey('HUHJsverovPJN3sVtv8J8D48fKzeajRtz3Ga4Zmh4RLA')
) {
  const [data] = updateSingleReserveConfigStruct.serialize({
    instructionDiscriminator: updateSingleReserveConfigInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.lendingMarketOwner,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.lendingMarket,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.reserve,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
