/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * @category Instructions
 * @category UpdateUserMetadataOwner
 * @category generated
 */
export type UpdateUserMetadataOwnerInstructionArgs = {
  owner: web3.PublicKey
}
/**
 * @category Instructions
 * @category UpdateUserMetadataOwner
 * @category generated
 */
export const updateUserMetadataOwnerStruct = new beet.BeetArgsStruct<
  UpdateUserMetadataOwnerInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['owner', beetSolana.publicKey],
  ],
  'UpdateUserMetadataOwnerInstructionArgs'
)
/**
 * Accounts required by the _updateUserMetadataOwner_ instruction
 *
 * @property [_writable_] userMetadata
 * @category Instructions
 * @category UpdateUserMetadataOwner
 * @category generated
 */
export type UpdateUserMetadataOwnerInstructionAccounts = {
  userMetadata: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const updateUserMetadataOwnerInstructionDiscriminator = [
  83, 111, 21, 58, 230, 131, 5, 236,
]

/**
 * Creates a _UpdateUserMetadataOwner_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category UpdateUserMetadataOwner
 * @category generated
 */
export function createUpdateUserMetadataOwnerInstruction(
  accounts: UpdateUserMetadataOwnerInstructionAccounts,
  args: UpdateUserMetadataOwnerInstructionArgs,
  programId = new web3.PublicKey('HUHJsverovPJN3sVtv8J8D48fKzeajRtz3Ga4Zmh4RLA')
) {
  const [data] = updateUserMetadataOwnerStruct.serialize({
    instructionDiscriminator: updateUserMetadataOwnerInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.userMetadata,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
