/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category UpdateEntireReserveConfig
 * @category generated
 */
export type UpdateEntireReserveConfigInstructionArgs = {
  mode: beet.bignum
  value: number[] /* size: 648 */
}
/**
 * @category Instructions
 * @category UpdateEntireReserveConfig
 * @category generated
 */
export const updateEntireReserveConfigStruct = new beet.BeetArgsStruct<
  UpdateEntireReserveConfigInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['mode', beet.u64],
    ['value', beet.uniformFixedSizeArray(beet.u8, 648)],
  ],
  'UpdateEntireReserveConfigInstructionArgs'
)
/**
 * Accounts required by the _updateEntireReserveConfig_ instruction
 *
 * @property [**signer**] lendingMarketOwner
 * @property [] lendingMarket
 * @property [_writable_] reserve
 * @category Instructions
 * @category UpdateEntireReserveConfig
 * @category generated
 */
export type UpdateEntireReserveConfigInstructionAccounts = {
  lendingMarketOwner: web3.PublicKey
  lendingMarket: web3.PublicKey
  reserve: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const updateEntireReserveConfigInstructionDiscriminator = [
  157, 46, 186, 160, 197, 57, 11, 253,
]

/**
 * Creates a _UpdateEntireReserveConfig_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category UpdateEntireReserveConfig
 * @category generated
 */
export function createUpdateEntireReserveConfigInstruction(
  accounts: UpdateEntireReserveConfigInstructionAccounts,
  args: UpdateEntireReserveConfigInstructionArgs,
  programId = new web3.PublicKey('HUHJsverovPJN3sVtv8J8D48fKzeajRtz3Ga4Zmh4RLA')
) {
  const [data] = updateEntireReserveConfigStruct.serialize({
    instructionDiscriminator: updateEntireReserveConfigInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.lendingMarketOwner,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.lendingMarket,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.reserve,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
