/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category WithdrawReferrerFees
 * @category generated
 */
export const withdrawReferrerFeesStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'WithdrawReferrerFeesInstructionArgs'
)
/**
 * Accounts required by the _withdrawReferrerFees_ instruction
 *
 * @property [_writable_, **signer**] referrer
 * @property [_writable_] referrerTokenState
 * @property [_writable_] reserve
 * @property [_writable_] reserveSupplyLiquidity
 * @property [_writable_] referrerTokenAccount
 * @property [] lendingMarket
 * @property [] lendingMarketAuthority
 * @category Instructions
 * @category WithdrawReferrerFees
 * @category generated
 */
export type WithdrawReferrerFeesInstructionAccounts = {
  referrer: web3.PublicKey
  referrerTokenState: web3.PublicKey
  reserve: web3.PublicKey
  reserveSupplyLiquidity: web3.PublicKey
  referrerTokenAccount: web3.PublicKey
  lendingMarket: web3.PublicKey
  lendingMarketAuthority: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const withdrawReferrerFeesInstructionDiscriminator = [
  171, 118, 121, 201, 233, 140, 23, 228,
]

/**
 * Creates a _WithdrawReferrerFees_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category WithdrawReferrerFees
 * @category generated
 */
export function createWithdrawReferrerFeesInstruction(
  accounts: WithdrawReferrerFeesInstructionAccounts,
  programId = new web3.PublicKey('HUHJsverovPJN3sVtv8J8D48fKzeajRtz3Ga4Zmh4RLA')
) {
  const [data] = withdrawReferrerFeesStruct.serialize({
    instructionDiscriminator: withdrawReferrerFeesInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.referrer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.referrerTokenState,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.reserve,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.reserveSupplyLiquidity,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.referrerTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarket,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarketAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
