/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category WithdrawProtocolFee
 * @category generated
 */
export type WithdrawProtocolFeeInstructionArgs = {
  amount: beet.bignum
}
/**
 * @category Instructions
 * @category WithdrawProtocolFee
 * @category generated
 */
export const withdrawProtocolFeeStruct = new beet.BeetArgsStruct<
  WithdrawProtocolFeeInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['amount', beet.u64],
  ],
  'WithdrawProtocolFeeInstructionArgs'
)
/**
 * Accounts required by the _withdrawProtocolFee_ instruction
 *
 * @property [**signer**] lendingMarketOwner
 * @property [] lendingMarket
 * @property [] reserve
 * @property [] lendingMarketAuthority
 * @property [_writable_] feeVault
 * @property [_writable_] lendingMarketOwnerAta
 * @category Instructions
 * @category WithdrawProtocolFee
 * @category generated
 */
export type WithdrawProtocolFeeInstructionAccounts = {
  lendingMarketOwner: web3.PublicKey
  lendingMarket: web3.PublicKey
  reserve: web3.PublicKey
  lendingMarketAuthority: web3.PublicKey
  feeVault: web3.PublicKey
  lendingMarketOwnerAta: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const withdrawProtocolFeeInstructionDiscriminator = [
  158, 201, 158, 189, 33, 93, 162, 103,
]

/**
 * Creates a _WithdrawProtocolFee_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category WithdrawProtocolFee
 * @category generated
 */
export function createWithdrawProtocolFeeInstruction(
  accounts: WithdrawProtocolFeeInstructionAccounts,
  args: WithdrawProtocolFeeInstructionArgs,
  programId = new web3.PublicKey('HUHJsverovPJN3sVtv8J8D48fKzeajRtz3Ga4Zmh4RLA')
) {
  const [data] = withdrawProtocolFeeStruct.serialize({
    instructionDiscriminator: withdrawProtocolFeeInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.lendingMarketOwner,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.lendingMarket,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.reserve,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarketAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.feeVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lendingMarketOwnerAta,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
