/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type BigFractionBytes = {
  value: beet.bignum[] /* size: 4 */
  padding: beet.bignum[] /* size: 2 */
}

/**
 * @category userTypes
 * @category generated
 */
export const bigFractionBytesBeet = new beet.BeetArgsStruct<BigFractionBytes>(
  [
    ['value', beet.uniformFixedSizeArray(beet.u64, 4)],
    ['padding', beet.uniformFixedSizeArray(beet.u64, 2)],
  ],
  'BigFractionBytes'
)
