/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type CurvePoint = {
  utilizationRateBps: number
  borrowRateBps: number
}

/**
 * @category userTypes
 * @category generated
 */
export const curvePointBeet = new beet.BeetArgsStruct<CurvePoint>(
  [
    ['utilizationRateBps', beet.u32],
    ['borrowRateBps', beet.u32],
  ],
  'CurvePoint'
)
