/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type InitObligationArgs = {
  tag: number
  id: number
}

/**
 * @category userTypes
 * @category generated
 */
export const initObligationArgsBeet =
  new beet.BeetArgsStruct<InitObligationArgs>(
    [
      ['tag', beet.u8],
      ['id', beet.u8],
    ],
    'InitObligationArgs'
  )
