/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type LastUpdate = {
  slot: beet.bignum
  stale: number
  placeholder: number[] /* size: 7 */
}

/**
 * @category userTypes
 * @category generated
 */
export const lastUpdateBeet = new beet.BeetArgsStruct<LastUpdate>(
  [
    ['slot', beet.u64],
    ['stale', beet.u8],
    ['placeholder', beet.uniformFixedSizeArray(beet.u8, 7)],
  ],
  'LastUpdate'
)
