/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type ReserveFees = {
  borrowFeeSf: beet.bignum
  flashLoanFeeSf: beet.bignum
  padding: number[] /* size: 8 */
}

/**
 * @category userTypes
 * @category generated
 */
export const reserveFeesBeet = new beet.BeetArgsStruct<ReserveFees>(
  [
    ['borrowFeeSf', beet.u64],
    ['flashLoanFeeSf', beet.u64],
    ['padding', beet.uniformFixedSizeArray(beet.u8, 8)],
  ],
  'ReserveFees'
)
