/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'
export type ReserveCollateral = {
  mintPubkey: web3.PublicKey
  mintTotalSupply: beet.bignum
  supplyVault: web3.PublicKey
  padding1: beet.bignum[] /* size: 32 */
  padding2: beet.bignum[] /* size: 32 */
}

/**
 * @category userTypes
 * @category generated
 */
export const reserveCollateralBeet = new beet.BeetArgsStruct<ReserveCollateral>(
  [
    ['mintPubkey', beetSolana.publicKey],
    ['mintTotalSupply', beet.u64],
    ['supplyVault', beetSolana.publicKey],
    ['padding1', beet.uniformFixedSizeArray(beet.u128, 32)],
    ['padding2', beet.uniformFixedSizeArray(beet.u128, 32)],
  ],
  'ReserveCollateral'
)
