/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { ReserveFees, reserveFeesBeet } from './ReserveFees'
import { BorrowRateCurve, borrowRateCurveBeet } from './BorrowRateCurve'
import { TokenInfo, tokenInfoBeet } from './TokenInfo'
import { WithdrawalCaps, withdrawalCapsBeet } from './WithdrawalCaps'
export type ReserveConfig = {
  status: number
  assetTier: number
  reserved0: number[] /* size: 2 */
  multiplierSideBoost: number[] /* size: 2 */
  multiplierTagBoost: number[] /* size: 8 */
  protocolTakeRatePct: number
  protocolLiquidationFeePct: number
  loanToValuePct: number
  liquidationThresholdPct: number
  minLiquidationBonusBps: number
  maxLiquidationBonusBps: number
  badDebtLiquidationBonusBps: number
  deleveragingMarginCallPeriodSecs: beet.bignum
  deleveragingThresholdSlotsPerBps: beet.bignum
  fees: ReserveFees
  borrowRateCurve: BorrowRateCurve
  borrowFactorPct: beet.bignum
  depositLimit: beet.bignum
  borrowLimit: beet.bignum
  tokenInfo: TokenInfo
  depositWithdrawalCap: WithdrawalCaps
  debtWithdrawalCap: WithdrawalCaps
  elevationGroups: number[] /* size: 20 */
  reserved1: number[] /* size: 4 */
}

/**
 * @category userTypes
 * @category generated
 */
export const reserveConfigBeet = new beet.BeetArgsStruct<ReserveConfig>(
  [
    ['status', beet.u8],
    ['assetTier', beet.u8],
    ['reserved0', beet.uniformFixedSizeArray(beet.u8, 2)],
    ['multiplierSideBoost', beet.uniformFixedSizeArray(beet.u8, 2)],
    ['multiplierTagBoost', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['protocolTakeRatePct', beet.u8],
    ['protocolLiquidationFeePct', beet.u8],
    ['loanToValuePct', beet.u8],
    ['liquidationThresholdPct', beet.u8],
    ['minLiquidationBonusBps', beet.u16],
    ['maxLiquidationBonusBps', beet.u16],
    ['badDebtLiquidationBonusBps', beet.u16],
    ['deleveragingMarginCallPeriodSecs', beet.u64],
    ['deleveragingThresholdSlotsPerBps', beet.u64],
    ['fees', reserveFeesBeet],
    ['borrowRateCurve', borrowRateCurveBeet],
    ['borrowFactorPct', beet.u64],
    ['depositLimit', beet.u64],
    ['borrowLimit', beet.u64],
    ['tokenInfo', tokenInfoBeet],
    ['depositWithdrawalCap', withdrawalCapsBeet],
    ['debtWithdrawalCap', withdrawalCapsBeet],
    ['elevationGroups', beet.uniformFixedSizeArray(beet.u8, 20)],
    ['reserved1', beet.uniformFixedSizeArray(beet.u8, 4)],
  ],
  'ReserveConfig'
)
