/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { PriceHeuristic, priceHeuristicBeet } from './PriceHeuristic'
import {
  ScopeConfiguration,
  scopeConfigurationBeet,
} from './ScopeConfiguration'
import {
  SwitchboardConfiguration,
  switchboardConfigurationBeet,
} from './SwitchboardConfiguration'
import { PythConfiguration, pythConfigurationBeet } from './PythConfiguration'
export type TokenInfo = {
  name: number[] /* size: 32 */
  heuristic: PriceHeuristic
  maxTwapDivergenceBps: beet.bignum
  maxAgePriceSeconds: beet.bignum
  maxAgeTwapSeconds: beet.bignum
  scopeConfiguration: ScopeConfiguration
  switchboardConfiguration: SwitchboardConfiguration
  pythConfiguration: PythConfiguration
  padding: beet.bignum[] /* size: 20 */
}

/**
 * @category userTypes
 * @category generated
 */
export const tokenInfoBeet = new beet.BeetArgsStruct<TokenInfo>(
  [
    ['name', beet.uniformFixedSizeArray(beet.u8, 32)],
    ['heuristic', priceHeuristicBeet],
    ['maxTwapDivergenceBps', beet.u64],
    ['maxAgePriceSeconds', beet.u64],
    ['maxAgeTwapSeconds', beet.u64],
    ['scopeConfiguration', scopeConfigurationBeet],
    ['switchboardConfiguration', switchboardConfigurationBeet],
    ['pythConfiguration', pythConfigurationBeet],
    ['padding', beet.uniformFixedSizeArray(beet.u64, 20)],
  ],
  'TokenInfo'
)
