/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type WithdrawalCaps = {
  configCapacity: beet.bignum
  currentTotal: beet.bignum
  lastIntervalStartTimestamp: beet.bignum
  configIntervalLengthSeconds: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const withdrawalCapsBeet = new beet.BeetArgsStruct<WithdrawalCaps>(
  [
    ['configCapacity', beet.i64],
    ['currentTotal', beet.i64],
    ['lastIntervalStartTimestamp', beet.u64],
    ['configIntervalLengthSeconds', beet.u64],
  ],
  'WithdrawalCaps'
)
